name: nora-soderlund/jira-summary-action
description: Posts a pull request comment with the summary of linked Jira stories.

branding:
  icon: info
  color: blue

inputs:
  JIRA_BASE_URL:
    description: The Jira base url
    required: true

  JIRA_USER_EMAIL:
    description: The Jira user email
    required: true

  JIRA_API_TOKEN:
    description: The Jira API token for the specified user email
    required: true

  JIRA_KEY:
    description: The project key prefix to look for - or the full story key.
    required: true

  GITHUB_TOKEN:
    description: The GitHub Token to use, e.g. GITHUB_TOKEN
    required: true

  JIRA_KEY_MULTIPLE:
    description: If true and JIRA_KEY is a project key, post a comment for every story key found.

  JIRA_PARTIAL_KEY_SILENT_FAILURE:
    description: If true, not finding a story key in a pull request if a project key is specified, only throws a silent error.

  DISABLE_PULL_REQUEST_COMMENT:
    description: If true, using the action will not create or update a pull request comment. Useful for only fetching the issue details from the output.

  IGNORE_BRANCHES:
    description: If source branch name mathces this regex ignore pull request.

outputs:
  key:
    description: The key of the Jira story.

  title:
    description: The title of the Jira story.

  description:
    description: The description of the Jira story in markdown.

runs:
  using: node20
  main: dist/index.js
